#!/bin/zsh
# Interactive git diff, with selection to add to the index
preview_command="git diff --color=always --stat {2}  | head -n1; git diff --color=always --exit-code -- {2} && bat {2}"

git -c color.status=always status --untracked-files=all -s |\
 fzf --reverse --no-sort --nth=2 --preview="$preview_command" \
 --preview-window="67%,~1" \
 --height=60% \
 --multi | \
 awk '{print$2}'

